#! /usr/bin/env bash

echo "---------------------------------------------------------"
echo "          Test DP syntax error handling                  "
echo "---------------------------------------------------------"
echo ""
echo "Action1: Select DP tab"
echo "Expect1: Error messages about DP syntax errors"
echo ""
echo "Action2: Click DP_no_plots"
echo "Expect2: Error message"
echo ""
echo "Action3: Click DP_syntax_error"
echo "Expect3: Error message"
echo ""
echo "Action4: Click DP_no_plots"
echo "Expect4: No messages - just doesn't do anything"
echo ""
echo "Action5: Click DP_good"
echo "Expect5: Expect plot"
echo ""
echo ""
koviz a.csv
echo ""
echo ""
